version: '3.7'

services:

  app:
    build: .
    command: python -m uvicorn --host=0.0.0.0 main:app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgres://postgres:test@db/postgres"
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test